name: ci
on: [push, pull_request]
jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [1.42.0, stable, beta, nightly]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - if: matrix.rust != 'nightly'
      run: rustup component add clippy
    - if: matrix.os != 'windows-latest' && matrix.rust != 'nightly'
      run: cargo clippy --all --all-features -- -D warnings
    - if: matrix.os != 'windows-latest'
      run: cargo build --verbose --all --all-features
    - if: matrix.os != 'windows-latest'
      run: cargo test --verbose --all --all-features
    - if: matrix.os == 'windows-latest' && matrix.rust != 'nightly'
      run: cargo clippy --all -- -D warnings
    - if: matrix.os == 'windows-latest'
      run: cargo build --verbose --all
    - if: matrix.os == 'windows-latest'
      run: cargo test --verbose --all

